name: Populate Labels

on:
  workflow_call:
    inputs:
      track_file_path:
        description: "Path to the .yaml file containing the tracks to populate the labels"
        required: true
        type: string
      label_prefix:
        description: "Prefix to add to each label"
        required: false
        default: ""
        type: string
      label_suffix:
        description: "Suffix to add to each label"
        required: false
        default: ""
        type: string
      source-branch:
        description: "GitHub branch to checkout. If blank, it will use default values."
        default: ''
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  populate-labels:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.source-branch }}
      - name: Install yq
        run: sudo snap install yq
      - name: Add labels to PR
        run: |
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          tracks=$(yq '.automatic_backport_tracks[]' ${{ inputs.track_file_path }})
          for track in $tracks; do
            echo "Found track ${track}..."
            full_label="${{ inputs.label_prefix }}${track}${{ inputs.label_suffix }}"

            # Create label if it doesn't already exist
            gh label create "$full_label" --color 05713A --description "Backport to $track" || true

            gh pr edit "${{ github.event.pull_request.number }}" --add-label "$full_label"
            echo "Added label ${full_label}!"
          done
          cat <<EOF > comment_body.txt
          ### ðŸ¤– Backport labels populated

          Labels to this pull request were added automatically by the \`populate-labels.yaml\` action.

          When the PR is merged, backport PRs according to the labels will be automatically created. To skip the backport creation, remove any unneeded labels before merging the PR.
          EOF
      - name: Post Comment
        run: |
          export GH_TOKEN=${{ secrets.GH_TOKEN }}

          # Post the comment using the simplified body file
          gh pr comment "${{ github.event.pull_request.number }}" --body-file comment_body.txt
